#pragma once

#include "Network/CMofMsg.h"
#include "Network/DCTNetwork.h"
#include "Logic/cltItemList.h"


class CMoFNetwork : public DCTNetwork {
public:
  CMoFNetwork();
  ~CMoFNetwork() override;
  void Initialize(void (__cdecl *a2)(unsigned __int8 *, unsigned __int16, unsigned int), unsigned int a3);
  void Poll();
  void OnRecv();
  int SetSendData(char *a2, unsigned __int16 a3);
  int Login(int a2);
  int Move(unsigned __int16 a2, unsigned __int16 a3, unsigned __int8 a4, unsigned __int16 a5);
  int Chatting(char *a2, unsigned __int8 a3, unsigned __int16 a4);
  int PartyChatting(char *a2);
  int Whisper(char *a2, char *a3);
  int MoveMap(unsigned __int16 a2);
  int ATTACK(unsigned int a2, unsigned int a3, int a4, unsigned __int8 a5, unsigned int *a6);
  int PickUpItem(unsigned __int16 a2, unsigned __int16 a3);
  int DropItem(unsigned __int16 a2, unsigned __int16 a3);
  int MoveItem(unsigned __int8 a2, unsigned __int8 a3);
  int UseItem(unsigned __int16 a2, char *a3, char *a4, char *a5, unsigned int a6, unsigned int a7, unsigned int a8, unsigned int a9, unsigned int a10);
  int BuyItem(unsigned __int16 a2, struct cltItemList *a3);
  int SellItem(unsigned __int16 a2, struct cltItemList *a3);
  int SysCommand(char *a2);
  int ApplyAbility(unsigned __int16 a2, unsigned __int16 a3, unsigned __int16 a4, unsigned __int16 a5);
  int AddToQuickSlot(unsigned __int8 a2, unsigned __int8 a3, unsigned __int8 a4, unsigned int a5);
  int DelFromQuickSlot(unsigned __int8 a2, unsigned __int8 a3);
  int MoveOnQuickSlot(unsigned __int8 a2, unsigned __int8 a3, unsigned __int8 a4);
  int EquipItem(unsigned __int8 a2, unsigned __int8 a3, unsigned __int16 a4);
  int UnEquipItem(unsigned __int8 a2, unsigned __int8 a3, unsigned __int16 a4);
  int UnEquipAllItem(unsigned int a2);
  int MoveEquipItem(unsigned __int8 a2, unsigned __int8 a3, unsigned int a4);
  int UpgradeClass(unsigned __int16 a2);
  int UpgradeClassGiftItem(unsigned __int16 a2);
  int RunState(unsigned __int8 a2);
  int UseSkill(unsigned __int16 a2, unsigned __int16 a3, unsigned int *a4);
  int LessonFinished(unsigned __int8 a2, unsigned int a3, unsigned int a4, unsigned __int8 a5, unsigned __int16 a6, unsigned int a7);
  int SetSchedule(unsigned __int16 a2, unsigned __int8 *a3);
  int CancelSchedule();
  int BuySkill(unsigned __int16 a2);
  int EnterMinigame();
  int LeaveMinigame();
  int GetMyChars(unsigned __int8 a2);
  int Auth(char *a2);
  int CreateChar(unsigned __int8 a2, char *a3, unsigned __int8 a4, unsigned __int16 a5, unsigned __int8 a6, unsigned __int8 a7, unsigned __int8 a8, unsigned __int8 a9, unsigned __int8 a10, unsigned __int8 a11, unsigned __int16 a12, unsigned __int16 a13, unsigned __int16 a14);
  int DeleteChar(int a2);
  int RequestJoinParty(char *a2);
  int ResponseJoinParty(unsigned __int8 a2);
  int LeaveParty();
  int KickOutParty(unsigned int a2);
  int RequestTrade(unsigned int a2);
  int ResponseTrade(unsigned __int8 a2);
  int RequestAddTradeItem(unsigned __int8 a2, unsigned __int16 a3);
  int RequestDeleteTradeItem(unsigned __int8 a2, unsigned __int16 a3);
  int RequestChangeTradeMoney(unsigned int a2);
  int RequestTradeDecision();
  int RequestTradeCancel();
  int AcceptQuest(unsigned __int16 a2);
  int RewardQuest(unsigned __int16 a2);
  int MeetNPC(unsigned __int16 a2);
  int GiveupQuest(unsigned __int16 a2);
  int EternalGiveupQuest(unsigned __int16 a2);
  int RequestCharDetailInfo(char *a2);
  int MyCharDead(int a2);
  int ServerLists(unsigned int a2);
  BOOL SendHeartBeat();
  int SendReturnOrderSheet(unsigned __int16 a2);
  int SendTeleportOrderSheet(unsigned __int16 a2, unsigned __int16 a3);
  int SendTeleportDragon(unsigned __int16 a2);
  int SendTakeShip(unsigned __int16 a2);
  int SendTownPortalOrderSheet(unsigned __int16 a2);
  int SendTownPortalReturn();
  int SalesAgencyJoin();
  int SalesAgencyQuit();
  int SalesAgencyRegist(unsigned __int16 a2, unsigned __int16 a3, unsigned int a4);
  int SalesAgencyGetMyList();
  int SalesAgencyCancelRegist(unsigned int a2, unsigned __int16 a3);
  int SalesAgencyGetSearchList(unsigned __int16 a2);
  int SalesAgencyBuyItem(unsigned int a2, unsigned __int16 a3, unsigned __int16 a4, unsigned __int16 a5);
  int SalesAgencyGetMyReturnList();
  int SalesAgencyGetMyReturnMoney();
  int SalesAgencyReceiveItem(unsigned int a2);
  int SalesAgencyReceiveMoney(unsigned int a2);
  int SalesAgencyGetAvgPrice(int a2, unsigned __int16 *a3);
  int LessonRanking(unsigned __int8 a2, int a3);
  int OpenStorage(char *a2);
  int OpenExStorage(char *a2);
  int CloseStorage();
  int CloseExStorage();
  int AddItemToStorage(unsigned __int8 a2, unsigned __int16 a3);
  int AddItemToExStorage(unsigned __int8 a2, unsigned __int16 a3);
  int DelItemFromStorage(unsigned __int8 a2, unsigned __int16 a3);
  int StorageCreatePW(char *a2);
  int StorageChangePW(char *a2, char *a3);
  int DelItemFromExStorage(unsigned __int8 a2, unsigned __int16 a3);
  int DepositMoney(int a2);
  int ExDepositMoney(int a2);
  int WithdrawingMoney(int a2);
  int ExWithdrawingMoney(int a2);
  int ExpandStorageGenericBag();
  int ExpandExStorageGenericBag(unsigned __int8 a2);
  int MoveItemStorage(unsigned __int8 a2, unsigned __int8 a3);
  int MoveItemExStorage(unsigned __int8 a2, unsigned __int8 a3);
  int RefreshFriendList();
  int AddFriendList(char *a2);
  int DelFriendList(char *a2);
  int GetFriendList();
  int AddBlackList(char *a2);
  int DelBlackList(char *a2);
  int GetBlackList();
  int RefreshBlackList();
  int GetRMonsterBook();
  int GetNpcBook();
  int StrikedMine(unsigned int a2, unsigned __int8 a3, unsigned int *a4);
  int RecallResponse(unsigned __int8 a2);
  int GetTestingBegin();
  int GetTestingFinished(unsigned __int8 a2, unsigned __int8 a3, char *a4, unsigned __int16 *a5);
  int AcquireSpecialty(unsigned __int16 a2);
  int MakingItem(unsigned __int16 a2, unsigned __int16 a3);
  int MakeCircle(char *a2, char *a3);
  int GetCircleInfo();
  int ReqAddCircleUser(char *a2);
  int ResAddcircleUser(unsigned __int8 a2, char *a3, char *a4);
  int DelCircleUser(char *a2);
  int DissolutionCircle();
  int LoginCircleUser();
  int LogoutCircleUser();
  int CircleChat(char *a2);
  int CircleQuestStart();
  int GetCircleRanking();
  int GetMyCircleRank();
  int ReqAddCircleSubMaster(char *a2);
  int ResAppointSubMaster(unsigned __int8 a2);
  int StartCircleQuiz();
  int SetCircleQuiz(unsigned __int16 a2, unsigned __int16 a3);
  int DeleteCircleQuiz();
  int CompleteCircleQuiz();
  int GetCircleQuiz();
  int TradeCut(unsigned __int8 a2);
  int WhisperCut(unsigned __int8 a2);
  int PartyCut(unsigned __int8 a2);
  int PartyListCut(unsigned __int8 a2);
  int AddFriendCut(unsigned __int8 a2);
  int AddCircleCut(unsigned __int8 a2);
  int AddStudentCut(unsigned __int8 a2);
  int GiveupCircleQuest();
  int FriendListSize();
  int AddCircleUserInmap();
  int DelCircleUserInmap();
  int SetCircleNotice(char *a2);
  int GetCircleNotice();
  int GetCircleUserList();
  int EnchantItem(unsigned __int8 a2, unsigned __int8 a3);
  int GUIDAckMsg(unsigned int a2, char *a3);
  int AckMsg(unsigned int a2, unsigned int a3, char *a4, unsigned __int8 a5);
  int OpenCashShop();
  int CloseCashShop();
  int MoveCashItem2Inven(int a2, __int64 *a3);
  int VerifyingCharName(char *a2);
  int BuyCashItem(unsigned __int8 a2, char *a3, unsigned __int8 a4, unsigned __int8 a5, int *a6);
  int UpdateCashMoney();
  int AddPrivateMarket(unsigned __int16 a2, unsigned __int16 a3, unsigned __int16 a4, unsigned int a5);
  int DelPrivateMarket(unsigned __int16 a2);
  int ClosePrivateMarket();
  int SetTitlePrivateMarket(char *a2);
  int ReadyPrivateMarket();
  int OpenPrivateMarket();
  int ExitPrivateMarket();
  int GetPrivateMarket(char *a2);
  int BuyPrivateMarket(char *a2, unsigned __int16 a3, unsigned __int16 a4, unsigned __int16 a5);
  int GetTitlePrivateMarket(char *a2);
  int ChildsDayEventBeginTime();
  int ChildsDayEventEndTime();
  int StartWarMeritorious(unsigned __int16 a2, unsigned __int16 a3, unsigned __int16 a4);
  int CompleteWarMeritorious();
  int StartSupplyMeritorious();
  int CompleteSupplyMeritorious();
  int RewardMeritoriousItem(unsigned __int16 a2);
  int SetCheerMessage(char *a2);
  int MakeMatch(unsigned __int8 a2, char *a3, unsigned __int16 a4, unsigned __int16 a5, char *a6, unsigned __int16 a7, unsigned __int8 a8);
  int JoinMatch(unsigned __int8 a2, char *a3);
  int ExitMatch(unsigned int a2, unsigned int a3);
  int MoveTeam(unsigned __int8 a2, unsigned int a3);
  int DestroyMatch();
  int StartMatch();
  int EscapeMatch();
  int GetCircleID();
  int WarpMatch(char *a2);
  int AcquireEmblem(unsigned __int16 a2);
  int SetUsingEmblem(unsigned __int16 a2);
  int SetQuizEvent(unsigned __int16 a2, unsigned __int16 a3);
  int DelQuizEvent();
  int CompleteQuizEvent();
  int FindPartyList();
  int GetPostIt(unsigned __int8 a2);
  int DelPostIt(unsigned int a2);
  int CheckIDPostIt(char *a2);
  int RequestStduent(char *a2);
  int ResponseStudent(unsigned __int8 a2);
  int DeleteTeacher();
  int DeleteStudent(char *a2);
  int RefreshTasList(unsigned __int8 a2);
  int SendTasPostit(char *a2, char *a3);
  int SetNickname(char *a2);
  int GiveupWarMeritorious();
  int GiveupSupMeritorious();
  int RecallNpc(unsigned __int16 a2);
  int TutorialStart();
  int TutorialEnd();
  int ChangeActionState(unsigned __int8 a2);
  int UseEmoticonItem(unsigned __int16 a2, unsigned __int16 a3);
  int SetSortItem(int a2);
  int Request_Server_Notify(int a2);
  int Request_Server_Memo(int a2);
  int MemoSaveToServer(unsigned __int8 a2, int a3, char *a4);
  int MemoDeleteToServer(int a2);
  int RequestComeinPartyMember(unsigned int a2);
  int SetNewTitle(unsigned __int16 a2);
  int RequestCreateIndun(int a2, unsigned __int8 a3, unsigned __int16 a4, unsigned __int16 a5);
  int InstansDungeonMoveMap(int a2);
  int RequestLeaveIndun();
  int JoinHighGradeShop();
  int LeaveHighGradeShop();
  int MapConquerorInfo();
  int MapCandidateInfo();
  int MapCandidateChallenge();
  int MapCandidateGiveup();
  int MapcandidateStart();
  int MapcandidatePause();
  int PetCreate(unsigned __int8 a2, unsigned __int16 a3);
  int PetSetActivity(unsigned __int8 a2);
  int PetMoveItemToInven(unsigned __int8 a2, unsigned __int16 a3);
  int PetMoveItemFromInven(unsigned __int8 a2, unsigned __int16 a3);
  int PetPickUpItem(unsigned __int16 a2, unsigned __int16 a3);
  int PetSetUsingSkill(unsigned __int8 a2, unsigned __int16 a3);
  int PetMoveItem(unsigned __int8 a2, unsigned __int8 a3);
  int PetReleaseUsingpet();
  int PetGetkeeping();
  int PetGetkeepingRelease();
  int PetKeeping();
  int PetReleaseKeepingPet(int a2);
  int PetTakeKeepingpet(int a2);
  int PetMarketSalepetlist();
  int PetMarketRegistry(int a2, char *a3, char *a4);
  int PetMarketSalePetInfo(int a2);
  int PetMarketMyPetInfo();
  int PetMarketMypetinfoRelease();
  int PetMarketRegistryCancel(int a2);
  int PetMarketAcceptMoney();
  int PetMarketBuyPet(int a2, char *a3);
  int PetMarketReregistry(int a2, int a3, char *a4, char *a5);
  int PKJoin(unsigned int a2, char *a3);
  int PKCreate(int a2, int a3, int a4, char *a5, char *a6, unsigned __int16 a7);
  int PKLeave();
  int PKReady();
  int PKReadyCancel();
  int PKBan(unsigned int a2);
  int PKStart();
  int PKMoveTeam(int a2);
  int PKSetSupport(int a2, char *a3);
  int PvPBuyItem(unsigned __int16 a2, struct cltItemList *a3);
  int ExpendCircleMembers(unsigned __int8 a2);
  int RequestLogin(char *a2, char *a3);
  int ShoutEventAnswer(char *a2);
  int AttendanceEventStart();
  int AttendanceEventEnd();
  int MarriagePropose(char *a2, char *a3, int a4, int a5);
  int MarriageProposeCancel(char *a2);
  int ResponsePropose(unsigned __int8 a2);
  int RequestMarriageDivorce();
  int RequestDivorceCancel();
  int RequestSpouseRecall();
  int RequestWeddingHallList();
  int RequestJoinWeddingHall(unsigned int a2);
  int RequestBegineWedding();
  int RequestGiveBouquet(char *a2);
  int RequestWeddingHallInfo();
  int RequestWeddingMoveMap(int a2);
  int UseTransport(unsigned __int16 a2);
  int CanChangeCharName(unsigned __int16 a2, char *a3);
  int ChangeCharName(unsigned __int16 a2, char *a3);
  int ItemSealLock(unsigned __int16 a2, unsigned __int16 a3);
  int ItemSealUnLock(unsigned __int16 a2, unsigned __int16 a3);
  char *CheckChatMsg(char *a2);
  static void __cdecl OnSocketClosed();
};
